### ISSUE TITLE
When .exe or .jar is ran nothing happens

### ISSUE THREAD

**Issue by levandejake** [Lymia/MPPatch#81] opened 2023-08-28 14:30 UTC
It doesn't run properly all I get is a log saying that its changing the files but nothing else.
It doesn't ask for a directory path or anything, no pop up at all.
I'm on Windows 10

[mppatch_installer.log](https://github.com/Lymia/MPPatch/files/12455413/mppatch_installer.log)

**Comment by Lymia** [comment] 2023-11-23 21:39
Duplicate of #66

**Closed by Lymia** 2023-11-23 21:39 UTC
Labels: Duplicate
