### ISSUE TITLE
Doesnt run on the latest OpenJDK  versions on windows.

### ISSUE THREAD

**Issue by gebbebebbebebr** [Lymia/MPPatch#69] opened 2022-05-06 21:23 UTC
The EXE and the jar file of the latest version does not want to run on the latest OpenJDK Java versions on windows for me. Downgrading to OpenJDK 8 fixed it for me. Perhaps it has to do something with this? https://stackoverflow.com/questions/65630568/java-error-java-util-prefs-windowspreferences-windowsregopenkey

Here's the console log output when running it.

```
» java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

```
```
» java -jar mppatch-0.1.3.jar

================================================================================
MPPatch version 0.1.3
Revision 8adb8b73, built on May 8, 2021 by jenkins@himawari

Build ID   : 3e5748f5-a000-46d0-87d3-cd86ca811320
Build Date : 2021-05-08T12:40:07Z
Revision   : 8adb8b735e884f26ae8e750339bbf213f8b556a4
Tree Status: <clean>
================================================================================

[2022-05-06T21:01:00Z/ INFO] Changing patch package...
Exception in thread "main" java.lang.NoSuchMethodError: Non-existent method WindowsRegOpenKey in java.util.prefs.WindowsPreferences was accessed.
        at moe.lymia.mppatch.util.win32.DynamicReflectiveProxy.applyDynamic(DynamicReflectiveProxy.scala:100)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$.moe$lymia$mppatch$util$win32$WindowsRegistry$$withKey(WindowsRegistry.scala:37)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$RegistryStringKey$.readKey(WindowsRegistry.scala:53)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$Hive.readKey(WindowsRegistry.scala:72)
        at moe.lymia.mppatch.util.win32.WindowsRegistry$Hive.apply(WindowsRegistry.scala:73)
        at moe.lymia.mppatch.core.Win32Platform$.defaultSystemPaths(platform.scala:75)
        at moe.lymia.mppatch.ui.MainFrame.pathFromRegistry(MainFrame.scala:91)
        at moe.lymia.mppatch.ui.MainFrame.<init>(MainFrame.scala:102)
        at moe.lymia.mppatch.ui.InstallerMain.main(Installer.scala:77)
        at moe.lymia.mppatch.ui.Installer$.main(Installer.scala:89)
        at moe.lymia.mppatch.ui.Installer.main(Installer.scala)
```

**Comment by Lymia** [comment] 2023-11-23 22:01
Duplicate of #74.

**Closed by Lymia** 2023-11-23 22:01 UTC
Labels: Duplicate
