### ISSUE TITLE
Perpetual crash back to menu

### ISSUE THREAD

**Issue by commissarr** [Lymia/MPPatch#67] opened 2021-12-01 10:18 UTC
multiplayer menu appears now in mod menu
selecting multiplayer from mod crashes after brief loading popup back to menu
zero multiplayer mod play
single player only
aka, zero change besides the MPPatch version subtitle at the bottom of the menu screen

**Comment by Lymia** [comment] 2023-12-15 17:45
Likely duplicate of #79

**Closed by Lymia** 2023-12-15 17:45 UTC
